config/routes.rb
RailsServer::Application.routes.draw do

  resources :users, only: [:new, :create, :update]

  match 'users/new' => 'users#new', via: :post
  match 'mylikes' => 'users#likes'
  match 'settings' => 'users#settings'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :images, only: [:show]
  resources :artists, only: [:show, :index]
  resources :categories, only: [:show, :index]
  resources :sources, only: [:show, :index]

  match '/chromebrowse', to: 'new_tab#show'
  match '/likes', to: 'new_tab#like', via: :post
  match '/dislikes', to: 'new_tab#dislike', via: :post

  match '/signup', to: 'static_pages#sign_up'
  match '/devices', to: 'static_pages#devices'
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/unsupported', to: 'static_pages#unsupported'
  match '/setcategories', to: 'static_pages#set_category_prefs'
  match '/savecategories', to: 'static_pages#save_category_prefs'
  match '/feedback', to: 'static_pages#feedback'
  match '/terms', to: 'static_pages#terms'
  match '/featured', to: 'static_pages#featured'
  match '/top', to: 'static_pages#top'
  root to: 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include NewTabHelper

  def home
    if signed_in?
      redirect_to featured_path
    end
  end

  def sign_up
    # create new User variable for users signing up via Facebook
    @user = User.new
  end

  def featured
    artistId = 309
    if Date.today.yday() % 2 == 1
       artistId = 311
    end
    @artist = Artist.find(artistId)
    render layout: "left_pane"
  end

  def top
    @images = Image.order("like_count DESC").first(15)
    render layout: "left_pane"
  end

  # new controller?

  def set_category_prefs

    # parse existing category prefs
    if current_user.category_prefs.nil?
      @category_settings = []
    else
      @category_settings = current_user.category_prefs.split(",").map(&:to_i)
    end

    # parse existing source prefs
    if current_user.source_prefs.nil?
      @source_settings = []
    else
      @source_settings = current_user.source_prefs.split(",").map(&:to_i)
    end

  end

  #TODO: edge case where we add new category between set and save
  def save_category_prefs

    # store user inputs
    current_user.category_prefs = params[:catSets].select{ |id| !id.empty? }.join(",")
    current_user.source_prefs = params[:srcSets].select{ |id| !id.empty? }.join(",")
    current_user.save(validate: false)

    # set next_image; used for pre-caching
    set_next_image

    flash[:success] = "Categories saved"
    redirect_to mylikes_path
  end
end

app/views/static_pages/_category_button.html.erb
<div class="category span3<% if clicked %> clicked<% end %>" cat_id="<%= category.id %>" title="<%= category.description %>">
<%= image_tag(category.thumbnail) %>
<h5><%= category.name %><h5>
</div>

app/views/static_pages/_install.html.erb
<button class="btn btn-large btn-primary" type="button" onclick="window.installExtension('<%= if signed_in? then featured_path else signup_path end %>')">Get Beautify for Browser</button>

app/views/static_pages/_source_button.html.erb
<div class="source span3<% if clicked %> clicked<% end %>" src_id="<%= source.id %>">
<%= image_tag(source.thumbnail) %>
<h5><%= source.name %></h5>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class="hero-unit">
<h1>About Us</h1>
<p>Our goal at Beautify is to help you effortlessly discover artwork that you love on any device. We do this by delivering personalized artwork to your digital devices. As you tell us what you like, our recommendations will get better and better.</p>
<% if false %><p>To get started, just <%= link_to "create an account", signup_path %>!</p><% end %>
<p>To get in touch with us, shoot us an email at <a href="mailto:GetBeautify@gmail.com">GetBeautify@gmail.com</a>.</p>
</div>

app/views/static_pages/devices.html.erb
<% provide(:title, 'Devices') %>
<div id="devices">
  <h1>Beautify your Browser</h1>
  <div id="install" class="row">
    <div class="span5 offset1">
      <p>Beautify for Browser delivers gorgeous new images every time you open a new tab. Click below to start using Beautify today!</p>
      <%= render "install" %>
    </div>
    <div class="span5">
      <%= image_tag "laptop.jpg" %>
    </div>
  </div>
  <div id="checkback" class="row center">
    <p>If you're on a mobile device, you can access a limited version of Beautify <%= link_to "here", featured_path %>.</p>
    <p>Beautify for Mobile is coming soon!</p>
  </div>
</div>

app/views/static_pages/featured.html.erb
<h1>Featured artist</h1>
<%= render @artist %>

app/views/static_pages/feedback.html.erb
<% provide(:title, 'Feedback') %>
<div class="hero-unit">
<h1>Feedback</h1>
<p>Beautify is currently in beta testing and we're looking for as much feedback as possible. Please let us know what you think of our service - the good, the bad, the ugly, and the beautiful - by emailing us at <a href="mailto:GetBeautify@gmail.com">GetBeautify@gmail.com</a>.</p>
</div>

app/views/static_pages/home.html.erb
<% provide(:extra_head) do %>
<style>
body {
  padding-top:0px;
  background-color: #DCE6F2;
}
</style>
<% end %>
<% provide(:hide_header, true) %>
<% provide(:hide_flash, true) %>
<% provide(:fluid, true) %>
<div class="home">
  <div class="row-fluid row-short row-white">
    <span class="span2 offset10">
      <%= link_to "Sign in", signin_path, id: "hlogin" %>
    </span>
  </div>
  <% if !flash.empty? %>
    <div class="row-fluid row-short row-white">
      <span class="span8 offset2">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <% end %>
      </span>
    </div>
  <% end %>
  <div class="row-fluid row-title row-white">
    <%= image_tag "home.jpg", id: "img1" %>
    <h1 id="title">Beautify</h1>
    <h2 id="subtitle">Effortlessly discover images you love.</h2>
    <%= render "install" %>
  </div>
  <div class="row-fluid">
    <h1>Effortless discovery</h1>
    <span class="span3 offset2">
      <p>Beautify is a browser add-on that shows you a new image every time you open a tab in your browser. You don't need to spend precious time finding beautiful art, photography, and fashion - we do that for you!</p>
    </span>
    <span class="span5">
      <%= image_tag "any_device.jpg" %>
    </span>
  </div>
  <div class="row-fluid row-white">
    <h1>Images you love</h1>
    <span class="span5 offset2">
      <%= image_tag "image_collage.jpg" %>
    </span>
    <span class="span3">
      <p>Discover inspiration from the thousands of images, paintings, and photographs in our curated collection.</p>
    </span>
  </div>
  <div class="row-fluid">
    <h1>Personalized</h1>
    <span class="span3 offset2">
      <p>Love impressionism? Let us know. Want landscape photography? We’ve got that too. Pick the categories you want and ‘like’ your favorite images. We'll personalize the images you receive.</p>
    </span>
    <span class="span5">
      <%= image_tag "category_display.jpg" %>
    </span>
  </div>
  <div class="row-fluid row-last">
    <%= render "install" %>
  </div>
</div>

app/views/static_pages/set_category_prefs.html.erb
<% provide(:title, 'Categories') %>
<div id="set_cats" class="center">
  <h1>Categories</h1>
  <h3>Please select the categories of images you'd like to receive.</h3>
  <h5>If you don't select any categories, we'll show you all of them! You can always change this later.</h5>
  <%= form_tag(savecategories_path, id: "saveCatsForm") do |l| %>
    <div class="row promotedTitle">Featured collections</div>
    <% promoted = [9,8,5] %>
    <div class="row promotedItems">
      <% promoted.each do |id| %>
        <%= render "source_button", source: Source.find(id), clicked: @source_settings.include?(id) %>
        <%= hidden_field_tag "srcSets[]", @source_settings.include?(id) ? id : "", id: "src_#{id}" %>
      <% end %>
    </div>
    <div class="row promotedLearn">
      <% promoted.each do |id| %>
        <div class="span3">
          <%= link_to "Learn more", Source.find(id), target: "_blank" %>
        </div>
      <% end %>
    </div>
    <div class="row">
      <% Category.all.each do |cat| %>
        <%= render "category_button", category: cat, clicked: @category_settings.include?(cat.id) %>
        <%= hidden_field_tag "catSets[]", @category_settings.include?(cat.id) ? cat.id : "", id: "cat_#{cat.id}" %>
      <% end %>
    </div>
    <div class="row"><%= submit_tag "Save", class: "btn btn-large btn-primary", id: "cat_btn" %></div>
  <% end %>
</div>

app/views/static_pages/sign_up.html.erb
<div id="signupbase">
  <h1>Sign up</h1>
  <p id="subtitle">Please sign up for a Beautify account. After that, you'll be able to specify the types of images you want.</p>
  <%= link_to "Sign up with Facebook", "#", class: "btn btn-large btn-primary fbButton" %>
  <div class="or">or</div>
  <%= link_to "Sign up with an email address", new_user_path, class: "email" %>
  <%= image_tag "home.jpg", id: "collage" %>
  <%= form_for @user, html: { id: "userForm" } do |f| %>
    <%= f.hidden_field :name, id: "nameField" %>
    <%= f.hidden_field :email, id: "emailField" %>
    <%= f.hidden_field :password, id: "passwordField" %>
    <%= f.hidden_field :password_confirmation, id: "confirmField" %>
  <% end %>
</div>

app/views/static_pages/terms.html.erb
<% provide(:title, 'Terms of Service') %>
<div class="hero-unit">
<h1>Terms of Service</h1>
<p>Artist descriptions are used under the Creative Commons Attribution Share-Alike license (CC-BY-SA). The text of the license is available <a href="http://creativecommons.org/licenses/by-sa/3.0/" target="_blank">here</a>.</p>
<p>Artwork used by Beautify is in affiliation with Art.com.</p>
<p>Photograph on home page is under the following license:
© Benh Lieu Song / Wikimedia Commons / <a href="http://creativecommons.org/licenses/by-sa/3.0/" target="_blank">CC-BY-SA-3.0</a> / <a href="http://en.wikipedia.org/wiki/Wikipedia:Text_of_the_GNU_Free_Documentation_License" target="_blank">GFDL</a>.</p>
</div>

app/views/static_pages/top.html.erb
<% provide(:title, "What's Hot?") %>
<div class="whatshot">
  <h1>What's Hot?</h1>
  <div class="hotcaption">The most liked images on Beautify.</div>
  <%= render @images %>
</div>

app/views/static_pages/unsupported.html.erb
<% provide(:title, 'Unsupported Browser') %>
<div class="center">
<h2 style="padding-top:50px;">Unsupported Browser</h2>
  <p>Unfortunately, we do not currently support the browser user are using. <a href="https://www.google.com/chrome" target="_blank">Please install Google Chrome</a>.</p>
  <img alt="Home" id="img1" src="/assets/home.jpg" style="padding-bottom: 20px; height: 400px;" >
  <p>If you're on a mobile device, you can access a limited version of Beautify <%= link_to "here", featured_path %>.</p>
  <p>Beautify for Mobile is coming soon!</p>
</div>