config/routes.rb
RailsServer::Application.routes.draw do

  resources :users, only: [:new, :create, :update]

  match 'users/new' => 'users#new', via: :post
  match 'mylikes' => 'users#likes'
  match 'settings' => 'users#settings'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :images, only: [:show]
  resources :artists, only: [:show, :index]
  resources :categories, only: [:show, :index]
  resources :sources, only: [:show, :index]

  match '/chromebrowse', to: 'new_tab#show'
  match '/likes', to: 'new_tab#like', via: :post
  match '/dislikes', to: 'new_tab#dislike', via: :post

  match '/signup', to: 'static_pages#sign_up'
  match '/devices', to: 'static_pages#devices'
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/unsupported', to: 'static_pages#unsupported'
  match '/setcategories', to: 'static_pages#set_category_prefs'
  match '/savecategories', to: 'static_pages#save_category_prefs'
  match '/feedback', to: 'static_pages#feedback'
  match '/terms', to: 'static_pages#terms'
  match '/featured', to: 'static_pages#featured'
  match '/top', to: 'static_pages#top'
  root to: 'static_pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation, :remember_token, :category_prefs, :source_prefs, :last_image, :last_image_time
  has_secure_password
  has_many :likes, dependent: :destroy

  before_save { |user| user.email = email.downcase }
  before_create :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true 

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:likes, :settings, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Beautify!"
      UserMailer.welcome_email(@user).deliver
      redirect_to setcategories_path # render 'static_pages/set_category_prefs' ?
    else
      render 'new'
    end
  end

  def likes
    @images = current_user.likes.map { |like| like.image }
    respond_to do |format|
      format.html {
        render layout: "left_pane"
      }
      format.json {
        render json: @images
      }
    end
  end

  def settings
    @user = current_user
  end

  def update
    if current_user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      redirect_to featured_path
    else
      @user = current_user
      render 'settings'
    end
  end

  private
 
    def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end

end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages' %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation %>

app/views/users/likes.html.erb
<% provide(:title, "My Likes") %>
<div class="showuser">
  <h1>My Likes</h1>
  <% if @images.any? %>
    <div class="showuserimages">
      <%= render @images %>
    </div>
  <% else %>
    <div class="nolikes">You don't have any likes yet. To get started, open a <a href="<%= chromebrowse_path %>" target="_blank">new tab</a> and tell us which images you enjoy!</div>
    <%= link_to image_tag("howToLike.jpg"), chromebrowse_path, target: "_blank" %>
  <% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>

<div class="signup">
  <h1>Beautify</h1>
  <%= form_for(@user) do |f| %>
    <%= render "fields", f: f %>
    <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/users/settings.html.erb
<% provide(:title, "Edit user") %>

<div class="edituser">
  <h1>Beautify</h1>
  <%= form_for(@user) do |f| %>
    <%= render 'fields', f: f %>
    <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
  <% end %>
</div>