config/routes.rb
RailsServer::Application.routes.draw do

  resources :users, only: [:new, :create, :update]

  match 'users/new' => 'users#new', via: :post
  match 'mylikes' => 'users#likes'
  match 'settings' => 'users#settings'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :images, only: [:show]
  resources :artists, only: [:show, :index]
  resources :categories, only: [:show, :index]
  resources :sources, only: [:show, :index]

  match '/chromebrowse', to: 'new_tab#show'
  match '/likes', to: 'new_tab#like', via: :post
  match '/dislikes', to: 'new_tab#dislike', via: :post

  match '/signup', to: 'static_pages#sign_up'
  match '/devices', to: 'static_pages#devices'
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/unsupported', to: 'static_pages#unsupported'
  match '/setcategories', to: 'static_pages#set_category_prefs'
  match '/savecategories', to: 'static_pages#save_category_prefs'
  match '/feedback', to: 'static_pages#feedback'
  match '/terms', to: 'static_pages#terms'
  match '/featured', to: 'static_pages#featured'
  match '/top', to: 'static_pages#top'
  root to: 'static_pages#home'

end

app/controllers/new_tab_controller.rb
class NewTabController < ApplicationController
  include NewTabHelper
  before_filter :signed_in_user, only: [:like, :dislike]

  def show
    @image = get_next_image
    increment_view_count(@image)
    set_next_image

    if signed_in?
      # instrumentation
      current_user.last_image = @image.id
      current_user.last_image_time = DateTime.now
      current_user.save(validate: false)
    end

    respond_to do |format|
      format.html { render :layout => false }
      format.json { render :json => @image }
    end
  end

  def like
    @like = current_user.likes.build(params[:like])
    @image = @like.image
    @image.like_count += 1
    respond_to do |format|
      if @like.save && @image.save
        format.js
      else
        #TODO: log error
      end
    end
  end

  def dislike
    #@dislike = current_user.dislikes.build(params[:dislike])
    @image = get_next_image
    increment_view_count(@image)
    set_next_image
    respond_to do |format|
      format.js
    end
  end

  private

    def signed_in_user
      if !signed_in?
        respond_to do |format|
          format.js { render action: 'redirect' }
        end
      end
    end

    def increment_view_count(image)
      if image.view_count.nil?
        image.view_count = 0
      end
      image.view_count += 1
      image.save(validate: false)
    end

end

app/helpers/new_tab_helper.rb
module NewTabHelper

  # get next image to show, checking cookie first
  def get_next_image

    image_id = cookies[:next_image]
    if(image_id.nil?) # no cookie
      image = generate_next_image
    else
      image = Image.find(image_id)
    end

    # return image
    image
  end

  # set next image to show; used for pre-caching
  def set_next_image
    next_image = generate_next_image
    cookies.permanent[:next_image] = next_image.id
  end

  private

    # get image satisfying category and source preferences
    def generate_next_image

      # not signed in, never set prefs, or set prefs to everything
      if !signed_in? || current_user.category_prefs.nil? || (current_user.category_prefs.empty? && (current_user.source_prefs.nil? || current_user.source_prefs.empty?))
        image = Image.first(:offset => rand(Image.count)) # random image
      else

        # parse category prefs
        category_prefs = current_user.category_prefs.split(",").map(&:to_i)

        # parse source prefs; could be nil for older users
        source_prefs = []
        if(!current_user.source_prefs.nil?)
          source_prefs = current_user.source_prefs.split(",").map(&:to_i)
        end

        # get image using prefs
        imagePool = Image.where("category_id IN (?) OR source_id IN (?)", category_prefs, source_prefs)
        image = imagePool.first(:offset => rand(imagePool.count))

      end

      # return image
      image
    end

end

app/views/new_tab/_attribution.html.erb
<div id="attr"><%= link_to "Beautify", if (signed_in?) then featured_path else root_path end, target: "_blank" %> © 2014, with help from <%= link_to image.source.name, image.source.link, target: "_blank" %>.</div>

app/views/new_tab/_controls.html.erb
<div class="controls<%= if defined?(invert) && invert then " invert" end %>" image_url="<%=image_url(image) %>">
  <% titleScope = [:images, :browse, :titles] %>

  <%= form_for(Like.new, remote: true, html: { id: "likeform" }) do |l| %>
    <%= l.hidden_field :image_id, value: image.id %>
    <span id="Like" class="button" title="<%= t(:like, scope: titleScope) %>"><i class="icon-heart"></i></span>
  <% end %>

  <%= form_tag("/dislikes", remote: true, id: "dislikeform") do |l| %>
    <%= hidden_field_tag :image_id, value: image.id %>
    <span id="Dislike" class="button" title="<%= t(:dislike, scope: titleScope) %>"><i class="icon-arrow-right"></i></span>
  <% end %>

  <div id="shareContainer">
    <div id="shareBtns">
      <a id="Facebook" href="#" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=<%= u image_url(image) %>', '_blank', 'width=626,height=436')">
        <%=image_tag("facebook.png") %>
      </a>
      <a id="Twitter" href="#" onclick="window.open('https://twitter.com/share?url=<%= u image_url(image) %>&text=<%= u image_display_name(image) %>&via=GetBeautify', '_blank', 'width=550,height=257')">
        <%=image_tag("twitter.png") %>
      </a>
      <a id="Pinterest" href="#" onclick="window.open('//pinterest.com/pin/create/button/?url=<%= u image_url(image) %>&media=<%= u image.image_url %>&description=<%= u image_display_name(image) + ' - Discovered using GetBeautify.com' %>', '_blank', 'width=746,height=316')">
        <%= image_tag("pinterest.png") %>
      </a>
    </div>
    <span id="Share" class="button" title="<%= t(:share, scope: titleScope) %>">
      <i class="icon-share"></i>
    </span>
  </div>

  <%= link_to content_tag(:i, "", class: "icon-shopping-cart"), image.buy_url, id: "Shop", class: "button", title: t(:browse, scope: titleScope), target: "_blank" %>
  <%= link_to content_tag(:i, "", class: "icon-home"), if (signed_in?) then featured_path else root_path end, id: "History", class: "button", title: t(:home, scope: titleScope), target: "_blank" %>

</div>

app/views/new_tab/_login_modal.html.erb
<div id="loginModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Please sign in</h3>
  </div>
  <div class="modal-body">
    <%= form_for(:session, url: sessions_path, remote: true) do |f| %>
      <div id="loginErr"></div>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
    <% end %>
    <p>New user? <%= link_to "Sign up now!", signup_path, target: "_blank" %></p>
  </div>
</div>

app/views/new_tab/_new_tab_image.html.erb
<div class="newTabImage">
  <a href="<%= image.buy_url %>" target="_blank" onclick="_gaq.push(['_trackEvent', 'Image', 'Buy', '<%= image.id %>'])">
    <img class="mainImg" src="<%= image.image_url %>"/>
  </a>
  <div class="artist"><%= image.artist.name %></div>
  <div class="name"><%= image.name %></div>
</div>

app/views/new_tab/dislike.js.erb
$('<img/>')[0].src = "<%= Image.find(cookies[:next_image]).image_url %>"

var $imageContainer = $(".imageContainer");
var $controlsContainer = $(".controlsContainer");
var $attrContainer = $(".attrContainer");

var $newImage = $("<%= escape_javascript(render "new_tab_image", image: @image) %>");
var $newControls = $("<%= escape_javascript(render "controls", image: @image) %>");
var $newAttr = $("<%= escape_javascript(render "attribution", image: @image) %>");

var $oldImage = $(".newTabImage");
$newImage.css("display", "none");

$oldImage.fadeOut(200, function() {
  $controlsContainer.html($newControls);
  $attrContainer.html($newAttr);
  $imageContainer.html($newImage);
  window.initBrowsePage();
  $newImage.fadeIn(200);
});

app/views/new_tab/like.js.erb
#TODO - this is js code that runs on client

app/views/new_tab/redirect.js.erb
$("<%= escape_javascript(render "login_modal") %>").modal();

app/views/new_tab/show.html.erb
<html>
<head>
  <title>Beautify</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/pre_cache' %>
  <%= render 'layouts/ga' %>
  <link href='//fonts.googleapis.com/css?family=Lora|Quattrocento+Sans' rel='stylesheet' type='text/css'>
</head>
<body class="newTab">
  <%= render 'layouts/fb' %>
  <div class="imageContainer">
    <%= render "new_tab_image", image: @image %>
  </div>
  <div class="controlsContainer">
    <%= render "controls", image: @image %>
  </div>
  <div class="attrContainer">
    <%= render "attribution", image: @image %>
  </div>
</body>
</html>