config/routes.rb
RailsServer::Application.routes.draw do

  resources :users, only: [:new, :create, :update]

  match 'users/new' => 'users#new', via: :post
  match 'mylikes' => 'users#likes'
  match 'settings' => 'users#settings'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :images, only: [:show]
  resources :artists, only: [:show, :index]
  resources :categories, only: [:show, :index]
  resources :sources, only: [:show, :index]

  match '/chromebrowse', to: 'new_tab#show'
  match '/likes', to: 'new_tab#like', via: :post
  match '/dislikes', to: 'new_tab#dislike', via: :post

  match '/signup', to: 'static_pages#sign_up'
  match '/devices', to: 'static_pages#devices'
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/unsupported', to: 'static_pages#unsupported'
  match '/setcategories', to: 'static_pages#set_category_prefs'
  match '/savecategories', to: 'static_pages#save_category_prefs'
  match '/feedback', to: 'static_pages#feedback'
  match '/terms', to: 'static_pages#terms'
  match '/featured', to: 'static_pages#featured'
  match '/top', to: 'static_pages#top'
  root to: 'static_pages#home'

end

app/views/layouts/_fb.html.erb
<div id="fb-root"></div>
<script>
  // Additional JS functions here
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '564327706941115', // App ID
      channelUrl : '//www.getbeautify.com/channel.html', // Channel File
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });

    // Additional init code here

  };

  // Load the SDK Asynchronously
  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="copyright">
    Beautify Copyright © 2014
  </div>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Feedback", feedback_path %></li>
      <li><%= link_to "Terms", terms_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_ga.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-40170822-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a href="<%= if(signed_in?) then featured_path else root_path end%>" class="brand">
        Beautify<sub>beta</sub>
      </a>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Settings", settings_path %></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_left_pane.html.erb
<ul class="nav nav-pills nav-stacked affix myLeftNav">
  <li><%= link_to "Featured", featured_path %></li>
  <li class="endSection"><%= link_to "What's hot?", top_path %></li>
  <li><%= link_to "My likes", mylikes_path %></li>
  <li><%= link_to "My categories", setcategories_path %></li>
  <li><%= link_to "My devices", devices_path %></li>
</ul>

app/views/layouts/_pre_cache.html.erb
<% if !cookies[:next_image].nil? %>
<script type="text/javascript">
$(document).ready(function() {
  $('<img/>')[0].src = "<%= Image.find(cookies[:next_image]).image_url %>"
});
</script>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# object: http://ogp.me/ns/object#">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/pre_cache' %>
    <%= render 'layouts/shim' %>
    <%= render 'layouts/ga' %>
    <link href='//fonts.googleapis.com/css?family=Lora|Quattrocento+Sans' rel='stylesheet' type='text/css'>
    <link rel="chrome-webstore-item" href="https://chrome.google.com/webstore/detail/objhpglpkbglppacglnkbaepdajkleec">
    <%= yield(:extra_head) %>
  </script>
  </head>
  <body>
    <%= render 'layouts/fb' %>
    <%= if !content_for?(:hide_header) then render 'layouts/header' end %>
    <div class="container<%= if content_for?(:fluid) then "-fluid" end%>">
      <% if !content_for?(:hide_flash) then flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end end %>
      <%= content_for?(:content) ? yield(:content) : yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/left_pane.html.erb
<% provide(:hide_flash, true) %>
<% provide :content do %>
  <div class="row lprow">
    <div class="span3">
      <%= render 'layouts/left_pane' %>
    </div>
    <div class="span9 offset3">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
    </div>
  </div>
<% end %>
<%= render template: "layouts/application" %>